"""Ajout des données d'admission

Revision ID: 0931c976f9aa
Revises: 10b9e705249b
Create Date: 2020-05-17 12:58:52.372601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0931c976f9aa'
down_revision = '10b9e705249b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(), nullable=True),
    sa.Column('prenom', sa.String(), nullable=True),
    sa.Column('profil', sa.String(), nullable=True),
    sa.Column('etablissement', sa.String(), nullable=True),
    sa.Column('ordreAppel', sa.Integer(), nullable=True),
    sa.Column('classement', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_candidat'))
    )
    op.create_table('statadmission',
    sa.Column('id_formation', sa.Integer(), nullable=False),
    sa.Column('id_candidat', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('etat', sa.String(), nullable=True),
    sa.Column('decision', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id_candidat'], ['candidat.id'], name=op.f('fk_statadmission_id_candidat_candidat')),
    sa.ForeignKeyConstraint(['id_formation'], ['formation.code'], name=op.f('fk_statadmission_id_formation_formation')),
    sa.PrimaryKeyConstraint('id_formation', 'id_candidat', 'timestamp', name=op.f('pk_statadmission'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('statadmission')
    op.drop_table('candidat')
    # ### end Alembic commands ###
