"""Initialisation

Revision ID: 10b9e705249b
Revises:
Create Date: 2020-02-28 15:02:51.722565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10b9e705249b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('formation',
    sa.Column('code', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('etablissement', sa.String(), nullable=False),
    sa.Column('type_formation', sa.String(), nullable=False),
    sa.Column('domaine', sa.String(), nullable=False),
    sa.Column('mention', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('code', name=op.f('pk_formation'))
    )
    op.create_table('seriebac',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nom', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_seriebac'))
    )
    op.create_table('special',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_special'))
    )
    op.create_table('typebac',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nom', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_typebac'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(length=255), nullable=False),
    sa.Column('password', sa.Unicode(length=255), nullable=False),
    sa.Column('last_logged', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('name', name=op.f('uq_users_name'))
    )
    op.execute("INSERT INTO users VALUES(1, 'test', 'test', NULL)")
    op.create_table('statdetail',
    sa.Column('id_formation', sa.Integer(), nullable=False),
    sa.Column('id_serie', sa.Integer(), nullable=False),
    sa.Column('id_typebac', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.Column('confirmes', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_formation'], ['formation.code'], name=op.f('fk_statdetail_id_formation_formation')),
    sa.ForeignKeyConstraint(['id_serie'], ['seriebac.id'], name=op.f('fk_statdetail_id_serie_seriebac')),
    sa.ForeignKeyConstraint(['id_typebac'], ['typebac.id'], name=op.f('fk_statdetail_id_typebac_typebac')),
    sa.PrimaryKeyConstraint('id_formation', 'id_serie', 'id_typebac', 'timestamp', name=op.f('pk_statdetail'))
    )
    op.create_table('statgenerale',
    sa.Column('id_formation', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('nb_voeux_total', sa.Integer(), nullable=True),
    sa.Column('nb_filles_total', sa.Integer(), nullable=True),
    sa.Column('nb_garcons_total', sa.Integer(), nullable=True),
    sa.Column('nb_boursiers_total', sa.Integer(), nullable=True),
    sa.Column('nb_non_boursiers_total', sa.Integer(), nullable=True),
    sa.Column('nb_voeux_confirmes', sa.Integer(), nullable=True),
    sa.Column('nb_filles_confirmes', sa.Integer(), nullable=True),
    sa.Column('nb_garcons_confirmes', sa.Integer(), nullable=True),
    sa.Column('nb_boursiers_confirmes', sa.Integer(), nullable=True),
    sa.Column('nb_non_boursiers_confirmes', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_formation'], ['formation.code'], name=op.f('fk_statgenerale_id_formation_formation')),
    sa.PrimaryKeyConstraint('id_formation', 'timestamp', name=op.f('pk_statgenerale'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('statgenerale')
    op.drop_table('statdetail')
    op.drop_table('users')
    op.drop_table('typebac')
    op.drop_table('special')
    op.drop_table('seriebac')
    op.drop_table('formation')
    # ### end Alembic commands ###
