"""Drapeau pour voir si voeu actif ou non

Revision ID: 23091a9facf6
Revises: 8df51229a0db
Create Date: 2021-01-31 13:12:06.837370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23091a9facf6'
down_revision = '8df51229a0db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voeu', schema=None) as batch_op:
        batch_op.add_column(sa.Column('actif', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voeu', schema=None) as batch_op:
        batch_op.drop_column('actif')

    # ### end Alembic commands ###
