"""Ajout du statut et origine dans les voeux

Revision ID: 5e1dfd1e9207
Revises: f8fa36b71568
Create Date: 2021-01-31 12:23:29.326993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e1dfd1e9207'
down_revision = 'f8fa36b71568'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voeu', schema=None) as batch_op:
        batch_op.add_column(sa.Column('origine', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('statut', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voeu', schema=None) as batch_op:
        batch_op.drop_column('statut')
        batch_op.drop_column('origine')

    # ### end Alembic commands ###
