"""CASCADEs

Revision ID: 8df51229a0db
Revises: 5e1dfd1e9207
Create Date: 2021-01-31 13:09:36.368899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8df51229a0db'
down_revision = '5e1dfd1e9207'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('options_voeux', schema=None) as batch_op:
        batch_op.drop_constraint('fk_options_voeux_id_voeu_voeu', type_='foreignkey')
        batch_op.drop_constraint('fk_options_voeux_id_optionbac_optionbac', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_options_voeux_id_voeu_voeu'), 'voeu', ['id_voeu'], ['id'], ondelete='cascade')
        batch_op.create_foreign_key(batch_op.f('fk_options_voeux_id_optionbac_optionbac'), 'optionbac', ['id_optionbac'], ['id'], ondelete='cascade')

    with op.batch_alter_table('specialites_voeux', schema=None) as batch_op:
        batch_op.drop_constraint('fk_specialites_voeux_id_specialitebac_specialitebac', type_='foreignkey')
        batch_op.drop_constraint('fk_specialites_voeux_id_voeu_voeu', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_specialites_voeux_id_specialitebac_specialitebac'), 'specialitebac', ['id_specialitebac'], ['id'], ondelete='cascade')
        batch_op.create_foreign_key(batch_op.f('fk_specialites_voeux_id_voeu_voeu'), 'voeu', ['id_voeu'], ['id'], ondelete='cascade')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('specialites_voeux', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_specialites_voeux_id_voeu_voeu'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_specialites_voeux_id_specialitebac_specialitebac'), type_='foreignkey')
        batch_op.create_foreign_key('fk_specialites_voeux_id_voeu_voeu', 'voeu', ['id_voeu'], ['id'])
        batch_op.create_foreign_key('fk_specialites_voeux_id_specialitebac_specialitebac', 'specialitebac', ['id_specialitebac'], ['id'])

    with op.batch_alter_table('options_voeux', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_options_voeux_id_optionbac_optionbac'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_options_voeux_id_voeu_voeu'), type_='foreignkey')
        batch_op.create_foreign_key('fk_options_voeux_id_optionbac_optionbac', 'optionbac', ['id_optionbac'], ['id'])
        batch_op.create_foreign_key('fk_options_voeux_id_voeu_voeu', 'voeu', ['id_voeu'], ['id'])

    # ### end Alembic commands ###
