"""Ajout des données d'admission

Revision ID: a32a544ffb96
Revises: 10b9e705249b
Create Date: 2020-05-17 13:51:50.578289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a32a544ffb96'
down_revision = '10b9e705249b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groupe',
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('libelle', sa.String(), nullable=True),
    sa.Column('places', sa.Integer(), nullable=True),
    sa.Column('nbAppel', sa.Integer(), nullable=True),
    sa.Column('id_formation', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_formation'], ['formation.code'], name=op.f('fk_groupe_id_formation_formation')),
    sa.PrimaryKeyConstraint('code', name=op.f('pk_groupe'))
    )
    op.create_table('candidat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(), nullable=True),
    sa.Column('prenom', sa.String(), nullable=True),
    sa.Column('profil', sa.String(), nullable=True),
    sa.Column('etablissement', sa.String(), nullable=True),
    sa.Column('ordreAppel', sa.Integer(), nullable=True),
    sa.Column('classement', sa.Integer(), nullable=True),
    sa.Column('id_groupe', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_groupe'], ['groupe.code'], name=op.f('fk_candidat_id_groupe_groupe')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_candidat'))
    )
    op.create_table('statadmission',
    sa.Column('id_candidat', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('etat', sa.String(), nullable=True),
    sa.Column('decision', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id_candidat'], ['candidat.id'], name=op.f('fk_statadmission_id_candidat_candidat')),
    sa.PrimaryKeyConstraint('id_candidat', 'timestamp', name=op.f('pk_statadmission'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('statadmission')
    op.drop_table('candidat')
    op.drop_table('groupe')
    # ### end Alembic commands ###
