"""Ajout de stats par specialite

Revision ID: f818c8b81a73
Revises: fc5535c5d11f
Create Date: 2021-01-27 22:08:52.842784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f818c8b81a73'
down_revision = 'fc5535c5d11f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('statspecialite',
    sa.Column('id_specialite', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('nb_voeux', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_specialite'], ['specialitebac.id'], name=op.f('fk_statspecialite_id_specialite_specialitebac')),
    sa.PrimaryKeyConstraint('id_specialite', 'timestamp', name=op.f('pk_statspecialite'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('statspecialite')
    # ### end Alembic commands ###
