"""Ajout du groupe et de la série dans les voeux

Revision ID: f8fa36b71568
Revises: f818c8b81a73
Create Date: 2021-01-29 18:16:27.975793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8fa36b71568'
down_revision = 'f818c8b81a73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voeu', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_groupe', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('id_serie', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_voeu_id_serie_seriebac'), 'seriebac', ['id_serie'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_voeu_id_groupe_groupe'), 'groupe', ['id_groupe'], ['code'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voeu', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_voeu_id_groupe_groupe'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_voeu_id_serie_seriebac'), type_='foreignkey')
        batch_op.drop_column('id_serie')
        batch_op.drop_column('id_groupe')

    # ### end Alembic commands ###
